In [1]:
# Import dependencies
import pandas as pd
import gmaps
import requests

In [2]:
#Import google API key
from config import g_key

In [3]:
#Create a df from the csv create with lat and lngs
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Busselton,AU,2021-10-25 16:28:37,-33.6500,115.3333,42.04,67,59,6.15
1,1,George,ZA,2021-10-25 16:28:37,-33.9630,22.4617,62.15,82,40,17.27
2,2,New Norfolk,AU,2021-10-25 16:28:37,-42.7826,147.0587,49.50,97,49,2.42
3,3,Bac Lieu,VN,2021-10-25 16:28:38,9.2850,105.7244,80.19,81,90,6.42
4,4,Kruisfontein,ZA,2021-10-25 16:28:38,-34.0033,24.7314,65.88,72,0,16.73

In [4]:
#Check to make sure lat, lng, temp, humidity, cloudiness, and windspeed are float or int.
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [5]:
#configure gmaps to use the google api key
gmaps.configure(api_key=g_key)

In [6]:
#Create a heatmap with tempuratures

# get the locations (lats and lngs)
locations = city_data_df[["Lat", "Lng"]]

#get the max temps
max_temp = city_data_df["Max Temp"]

#use and assign the figure variable
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.35)

#use and assign the heatmaps variable
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)

#Add the heatmap layer
fig.add_layer(heat_layer)

#Call and create the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
#Create a heatmap with humidity

# get the locations (lats and lngs)
locations = city_data_df[["Lat", "Lng"]]

#get the max temps
humidity = city_data_df["Humidity"]

#use and assign the figure variable
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.35)

#use and assign the heatmaps variable
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

#Add the heatmap layer
fig.add_layer(heat_layer)

#Call and create the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
#Create a heatmap with cloudiness

# get the locations (lats and lngs)
locations = city_data_df[["Lat", "Lng"]]

#get the max temps
clouds = city_data_df["Cloudiness"]

#use and assign the figure variable
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.35)

#use and assign the heatmaps variable
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

#Add the heatmap layer
fig.add_layer(heat_layer)

#Call and create the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
#Create a heatmap with wind speed

# get the locations (lats and lngs)
locations = city_data_df[["Lat", "Lng"]]

#get the max temps
wind = city_data_df["Wind Speed"]

#use and assign the figure variable
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.35)

#use and assign the heatmaps variable
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

#Add the heatmap layer
fig.add_layer(heat_layer)

#Call and create the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
#ask the customer to add min and max temp values
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 80

In [11]:
#filter through the data to find the cities with the min and max temp input
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] >= min_temp)].dropna()
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
14,14,Quatre Cocos,MU,2021-10-25 16:28:42,-20.2078,57.7625,75.31,76,22,16.96
26,26,Sao Joao Da Barra,BR,2021-10-25 16:26:59,-21.6403,-41.0511,75.29,74,91,10.56
36,36,Atuona,PF,2021-10-25 16:28:48,-9.8000,-139.0333,77.05,77,73,15.97
38,38,Cape Town,ZA,2021-10-25 16:25:10,-33.9258,18.4232,75.11,58,0,4.00
42,42,Bambous Virieux,MU,2021-10-25 16:28:49,-20.3428,57.7575,75.45,73,40,14.97
45,45,Cedar Hill,US,2021-10-25 16:26:57,32.5885,-96.9561,78.75,51,1,1.99
46,46,Asyut,EG,2021-10-25 16:27:30,27.1810,31.1837,77.86,34,0,10.76
50,50,Puerto Ayora,EC,2021-10-25 16:28:51,-0.7393,-90.3518,75.16,90,56,3.00
57,57,Ambilobe,MG,2021-10-25 16:28:53,-13.2000,49.0500,79.61,58,17,9.78
64,64,Port Moresby,PG,2021-10-25 16:25:19,-9.4431,147.1797,76.42,94,20,3.44

In [12]:
preferred_cities_df.isnull().sum()

City_ID       0
City          0
Country       0
Date          0
Lat           0
Lng           0
Max Temp      0
Humidity      0
Cloudiness    0
Wind Speed    0
dtype: int64

In [13]:
#create a hotel df with cities, country, max temp, and coordinates
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

                 City Country  Max Temp      Lat       Lng Hotel Name
14       Quatre Cocos      MU     75.31 -20.2078   57.7625
26  Sao Joao Da Barra      BR     75.29 -21.6403  -41.0511
36             Atuona      PF     77.05  -9.8000 -139.0333
38          Cape Town      ZA     75.11 -33.9258   18.4232
42    Bambous Virieux      MU     75.45 -20.3428   57.7575
45         Cedar Hill      US     78.75  32.5885  -96.9561
46              Asyut      EG     77.86  27.1810   31.1837
50       Puerto Ayora      EC     75.16  -0.7393  -90.3518
57           Ambilobe      MG     79.61 -13.2000   49.0500
64       Port Moresby      PG     76.42  -9.4431  147.1797

In [14]:
#search for a hotel and set parameters
params = {"radius": 5000,
         "type": "lodging",
         "key": g_key
         }

In [15]:
#iterate through the dataframe
for index, row in hotel_df.iterrows():
    
    #get the lat and lng
    lat = row["Lat"]
    lng = row["Lng"]
    
    #add the lat and lng to the location key for the params dictionary
    params["location"] = f"{lat},{lng}"
    
    #use the search term: lodging and lat and lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    #make the request and get the json data from the search
    hotels = requests.get(base_url, params=params).json()
    
    #get the first hotel from the results and store the name
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping")

Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping

In [16]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
14,Quatre Cocos,MU,75.31,-20.2078,57.7625,Sunrise Attitude Hotel
26,Sao Joao Da Barra,BR,75.29,-21.6403,-41.0511,Pousada Porto De Canoas
36,Atuona,PF,77.05,-9.8000,-139.0333,Villa Enata
38,Cape Town,ZA,75.11,-33.9258,18.4232,Southern Sun Waterfront Cape Town
42,Bambous Virieux,MU,75.45,-20.3428,57.7575,Casa Tia Villa
45,Cedar Hill,US,78.75,32.5885,-96.9561,Holiday Inn Express & Suites Dallas Southwest-...
46,Asyut,EG,77.86,27.1810,31.1837,Florence Hotel Assiut
50,Puerto Ayora,EC,75.16,-0.7393,-90.3518,Finch Bay Galapagos Hotel
57,Ambilobe,MG,79.61,-13.2000,49.0500,Hôtel & Restaurant DIANA Ambilobe
64,Port Moresby,PG,76.42,-9.4431,147.1797,Lamana Hotel (Port Moresby)

In [33]:
#Create a heatmap with tempuratures

# get the locations (lats and lngs)
locations = hotel_df[["Lat", "Lng"]]

#get the max temps
max_temp = hotel_df["Max Temp"]

#use and assign the figure variable
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.35)

#use and assign the heatmaps variable
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)

#Add the heatmap layer
fig.add_layer(heat_layer)

#add marker layer
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(marker_layer)

#Call and create the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [34]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [35]:
#store the df row
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [36]:
#Create a heatmap with tempuratures

# get the locations (lats and lngs)
locations = hotel_df[["Lat", "Lng"]]

#get the max temps
max_temp = hotel_df["Max Temp"]

#use and assign the figure variable
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.35)

#use and assign the heatmaps variable
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)

#Add the heatmap layer
fig.add_layer(heat_layer)

#add marker layer
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

#Call and create the figure
fig

Figure(layout=FigureLayout(height='420px'))